name: Wiki Sync

on:
  # Manual trigger (e.g. first-time population / re-sync)
  workflow_dispatch: {}

  push:
    branches:
    - main
    paths:
    - 'pages/**'

jobs:
  sync:

    name: Synchronize Wiki
    runs-on: ubuntu-latest
    if: github.repository == 'Slimefun5/wiki'

    steps:
    - name: Checking out repository
      uses: actions/checkout@v4

    - name: Syncing to github-wiki
      run: sh src/sync.sh
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
